services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BASE_ADDRESS=http://host.docker.internal:8090
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    # Для тестів включаємо режим відлагодження, коли балансувальник додає інформацію, кому було відправлено запит.
    command: ["lb", "--trace=true"]
